Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
Metrics/LineLength:
  Max: 120
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

