version: "2"
services:
  nginx:
    image: nginx:1.16.1
    ports:
      - 80:80
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_web
    ports:
      - 3000:3000
  scheduler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_scheduler

