FROM python:3.7.4

RUN apt-get update -yq
RUN apt-get install -yq python-dev git scons swig

RUN git clone https://github.com/jgarff/rpi_ws281x.git

RUN cd rpi_ws281x && scons
RUN cd rpi_ws281x/python && python3 setup.py build && python3 setup.py install

WORKDIR /app

ADD ./lib/leds ./lib/leds

RUN python -u lib/leds/leds_listener.py
