name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ruby:2.5.1
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Rspec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
